apiVersion: apps/v1
kind: Deployment
metadata:
  name: legacydbmig-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: legacydbmig-web
  template:
    metadata:
      labels:
        app: legacydbmig-web
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
        - name: legacydbmig-web
          image: acrlegacydbmigdevizahjk.azurecr.io/legacydbmig-web:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: acr-secret