-- PostgreSql migration script for LegacyDatabaseMigrationPOC.
-- Generated by Database\Setup-Database.ps1 -GenerateScripts (ef6.exe, EntityFramework 6.5.2). Do not edit by hand.
-- Takes an EMPTY database to the latest EF6 migration and records it in dbo.__MigrationHistory,
-- so the application and Update-Database treat the schema as fully migrated.
-- Every migration is wrapped in a DO block that skips it when dbo.__MigrationHistory already lists it, so the script is safe to re-run.
-- The database itself must already exist: Setup-Database.ps1 -ApplyScripts creates it and then
-- runs this file followed by SeedData.sql.

-- Migration 202609071103352_InitialCreate
DO $ef6migration$
BEGIN
    IF to_regclass('dbo."__MigrationHistory"') IS NOT NULL THEN
        IF EXISTS (SELECT 1 FROM dbo."__MigrationHistory" WHERE "MigrationId" = '202609071103352_InitialCreate') THEN
            RAISE NOTICE 'Migration 202609071103352_InitialCreate is already applied, skipping.';
            RETURN;
        END IF;
    END IF;

    CREATE SCHEMA IF NOT EXISTS "dbo";
    CREATE TABLE "dbo"."Customers"("Id" serial4 NOT NULL,"FirstName" varchar(100) NOT NULL,"LastName" varchar(100) NOT NULL,"Email" varchar(200),"CreatedAt" timestamp NOT NULL,"IsActive" boolean NOT NULL,CONSTRAINT "PK_dbo.Customers" PRIMARY KEY ("Id"));
    CREATE TABLE "dbo"."__MigrationHistory"("MigrationId" varchar(150) NOT NULL,"ContextKey" varchar(300) NOT NULL,"Model" bytea NOT NULL,"ProductVersion" varchar(32) NOT NULL,CONSTRAINT "PK_dbo.__MigrationHistory" PRIMARY KEY ("MigrationId","ContextKey"));
    INSERT INTO "dbo"."__MigrationHistory"("MigrationId","ContextKey","Model","ProductVersion") VALUES (E'202609071103352_InitialCreate',E'LegacyDatabaseMigrationPOC.Migrations.Configuration',decode('H4sIAAAAAAAEAM1Yy3IaORTdT9X8g0prBwGeRcbVJEXAnqLGGFdwshfdF6yKWuq01C74tlnkk/ILuer3AzA4rmSKDdyWzn3o3qPTfP/vm/d+G0ryBLERWo3ooNenBJSvA6E2I5rY9Zu39P27P//wroNwSz4X6y7dOtypzIg+WhtdMWb8Rwi56YXCj7XRa9vzdch4oNmw3/+bDQYMEIIiFiHex0RZEUL6A39OtPIhsgmXcx2ANLkdnyxTVHLHQzAR92FEb2HD/d2UW77iBuZiE3OLMd0vJj1npGQsBcewliDXlHCltE0XXH0ysLSxVptlhAYuH3YR4Lo1lwbyZK6q5afm1R+6vFi1sYDyE2N1eCbg4DIvFGtvf1G5aVlILOU1ltzuXNZpOUd0krqAmJK2s6uJjN3Co9XOjqpXoFyQw2svys7BBnOfCzJJpE1iGClIbMzlBblPVlL4/8LuQX8BNVKJlPXwMQF81jCg6T7WEcR29xHWeVKzgBLW3MfaG8tttT1ZujNlL4eU3KFzvpJQdketNEurY/gHFGB2ENxzayFWDgPS+na8t3zdiNhY97VwiT2Js0bJnG9vQW3sI05hH6frRmwhKCx5GJ+UwNHETTZOYE+Yx13f8t/l+TrkQh5xOzzR7XEvkxjckYxt4QlbER5EeH68MzP2rXgqK/VBawlcPYPjsWrEuoOHHGe5wLbJfYyjaLpyRtjaPROIbJUPocmzb0acgS7BtobZUFJFkbFgrxr0feGWgVWsyzLaLeiZHeBnb86jCM+yxte5hSwzsp68WZ5PXGGGwXyzh7/KaEtPOI98A62n6BojTYetICRKJkHYWdY4hgMlLly1K91mo6rwxQ73PR++49dWdUYt0KqmN5hmiCSTZgxlcDUe72xNL1AuebyH8CZaJqE6RJrHdtcorA5SM5+OVXFSHaqyno6Uc0wdJjedjlFjkDpOzXw6VsUhjUqX1i6Sx1on3e4v1mmw1kXX7thj095eUnovp7413V4+ac9LtM7oZUsowRI9icCN3V20MV9lZZlzJdZgbHb508Hb3mVLyf1/VBUzJpAnSqtfrmCEsn9R8qxIOfNC7KiWJx77jzzuioef1CSvhdtQHPtAh03QF+kL9wpjLA+jnxYYKxQYr6ouurffafLhqHrIxnhEg5XGwLNIa7rjheKiSyseq78felMwYlNBuLdFBb4b3wq0WDNTa13UGrOrR1QsaR3FHCwPsEjj2Io19y0+9sGYVKJ+5jJJm2kFwUwtEhsldmwMhCvZEPoeO+4/VVDNmL1F5H6Z10gBwxSYAizUh0TIoIz7Zk8XHYBw/ZLzBUaFEh3hNrsS6U6rE4Hy8k0hAuXY5gHCSCKYWagldw1/fmwohTP1VFwWh0GeP4hm2b2p4KjEQpNjVPvdfx7M/enx7gfCy+k5JhEAAA==', 'base64'),E'6.5.2');
END
$ef6migration$;

