apiVersion: v1
kind: ServiceAccount
metadata:
  name: legacydbmig-sa
  namespace: legacydbmig
  annotations:
    # CHANGE: terraform output workload_identity_client_id
    azure.workload.identity/client-id: "607c22a5-19a9-497b-bc4e-59b537e0e403"
  labels:
    azure.workload.identity/use: "true"
